name: Generate JioTV Playlist

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build JioTV Go
        run: |
          git clone https://github.com/jiotv-go/jiotv_go
          cd jiotv_go
          go build

      - name: Install and Run Cloudflare Warp (Bypass IP Block)
        run: |
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt-get update && sudo apt-get install cloudflare-warp -y
          warp-cli --accept-tos registration new
          warp-cli --accept-tos mode proxy
          warp-cli --accept-tos proxy port 40000
          warp-cli --accept-tos connect
          sleep 3

      - name: Create Config File
        run: |
          mkdir -p ~/.config/jiotv_go
          cat << 'EOF' > ~/.config/jiotv_go/config.toml
          ${{ secrets.JIO_CONFIG }}
          EOF

      - name: Generate EPG and Playlist via Proxy
        env:
          HTTP_PROXY: "socks5://127.0.0.1:40000"
          HTTPS_PROXY: "socks5://127.0.0.1:40000"
        run: |
          cd jiotv_go
          ./jiotv_go epg generate
